version: '3.8'

services:
  mermaid-app:
    build: .
    container_name: mermaid-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "127.0.0.1:3002:3000" # Expos√© sur localhost:3002
    volumes:
      - ./logs:/app/logs # Pour les logs de l'application
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
